### ISSUE TITLE
GET requests with no body have error: 215122 Signature validation failed

### ISSUE THREAD

**Issue by alexdawn** [eBay/digital-signature-php-sdk#13]
First of all thank you for providing an example that uses the ebay api. The Unit tests work fine. :+1: 

The example code also works against the supplied sandbox endpoint with my own keys/tokens. :+1: 

My own implementation (also using the phpsec lib) had been generating 215122 errors on both live and the sandbox, so I thought I would check against your example code, and I'm getting the same issue:

* changing to my own user token generated from the dev site
* Getting the keys ED25519 from `https://apiz.sandbox.ebay.com/developer/key_management/v1/signing_key`
* storing them in `examples/example-config.json` and `examples/keys/ed25519/privatekey.pem`
* change the endpoint  to `https://apiz.sandbox.ebay.com/sell/finances/v1/transaction` which is a GET safe for running on both sandbox and live
* change the GET to PUT
* change the body to null as the request has no body and hence no content-digest
* Running `examples/example.php` I get:

```json
{
  "errors": [
    {
      "errorId": 215122,
      "domain": "ACCESS",
      "category": "REQUEST",
      "message": "Signature validation failed",
      "longMessage": "Signature validation failed to fulfill the request."
    }
  ]
}
```

and `curl_getinfo($ch);` gives:

```php
"array (
  'url' => 'https://apiz.sandbox.ebay.com/sell/finances/v1/transaction',
  'content_type' => 'application/json; charset=utf-8',
  'http_code' => 403,
  'header_size' => 220,
  'request_size' => 3608,
  'filetime' => -1,
  'ssl_verify_result' => 0,
  'redirect_count' => 0,
  'total_time' => 0.730208,
  'namelookup_time' => 0.031561,
  'connect_time' => 0.185171,
  'pretransfer_time' => 0.543139,
  'size_upload' => 0.0,
  'size_download' => 236.0,
  'speed_download' => 323.0,
  'speed_upload' => 0.0,
  'download_content_length' => 236.0,
  'upload_content_length' => 0.0,
  'starttransfer_time' => 0.730172,
  'redirect_time' => 0.0,
  'redirect_url' => '',
  'primary_ip' => '*************',
  'certinfo' => 
  array (
  ),
  'primary_port' => 443,
  'local_ip' => '***************',
  'local_port' => ***********,
  'http_version' => 2,
  'protocol' => 2,
  'ssl_verifyresult' => 0,
  'scheme' => 'HTTPS',
  'appconnect_time_us' => 542945,
  'connect_time_us' => 185171,
  'namelookup_time_us' => 31561,
  'pretransfer_t"
```

**Comment by piniyini** [comment]
Hello Alex

Can you believe I've been trying to run this code all day?! The exact same scenario and I thought I was doing something wrong.

Did you manage to get this fixed?

Regards

**Comment by alexdawn** [comment]
@piniyini afraid not given it's bugged for two seperate SDKs I concluded it is probably a server problem wrongly creating the signature base. Other types of request work fine and I don't need the problematic endpoint

**Comment by uherberg** [comment]
@alexdawn and @piniyini : A colleague of mine tried to reproduce what you observed, but couldn't. I will also try it. We have hundreds of customers who were able to correctly implement it, so I assume it's maybe an edge case. I will update here later today or tomorrow.

**Comment by uherberg** [comment]
@alexdawn and @piniyini I found the cause; It's a bug in the SDK. The "content-digest" is still included in the signature-input header, so the server correctly rejects such a request without body. I will issue a fix for the SDK soon. Thanks for pointing this out!

**Comment by uherberg** [comment]
https://github.com/eBay/digital-signature-php-sdk/pull/14 should fix the issue

**Comment by uherberg** [comment]
@alexdawn and @piniyini Can you check if it works now? Then I would close this issue.

**Comment by piniyini** [comment]
Hello @uherberg 

Tried a few times now, with both security keys and can't get it to work. I might be doing something wrong though as I've been round the block on this one and my brain is fried. You're more than welcome to collab on my AWS Cloud9.

Thanks

**Comment by uherberg** [comment]
@piniyini Which error message do you get? Make sure to use sandbox credentials for sandbox, and production credentials for production APIs.

**Comment by piniyini** [comment]
@uherberg I've noticed I'm still getting `[Signature-Input] => sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1681321724` content-digest is still included

eventhough I've got the $body param as null
`$headers = $signature->generateSignatureHeaders($headers, $endpoint, "GET", null);`

**Comment by piniyini** [comment]
@uherberg Figured it out, I had `content-digest` in my `digital-signature-php-sdk/examples/example-config.json` file, once removed it worked!
But maybe there should be a way to remove this if its a GET request?
Thanks for fixing

**Comment by uherberg** [comment]
@piniyini Yikes, that's what I was trying to fix. Removing it from the config.json already worked before, but if you have multiple calls in your code (POST and GET), you would need the content-digest for POSTs. Let me check again.

**Comment by uherberg** [comment]
@piniyini Ah, I forgot to automatically increase the version in the github tag, so that Packagist would pick it up. We will add that soon. For now, I manually pushed the new version. Can you try it again please? (run `composer update` to update to the latest version 1.0.4)

**Comment by piniyini** [comment]
Hello @uherberg 

I've now upgraded to 1.0.4 via `composer update` but still no luck, I leave `"content-digest"` inside `signatureParams` and it **does not** appear in 
`[Signature-Input] => sig1=("x-ebay-signature-key" "@method" "@path" "@authority");created=1681331212`

however the GET request still fails. If I take out `"content-digest"` then the call goes through.

I think the bug is still alive.

**Comment by uherberg** [comment]
@piniyini I wasn't able to reproduce it. Here is the exact code I used:

```
$signature = new Signature("example-config.json");
$endpoint = 'https://apiz.sandbox.ebay.com/sell/finances/v1/transaction';
const USER_TOKEN = 'v^1.1#i^1#I^3...';
$headers = [
    'Authorization' => 'Bearer ' . USER_TOKEN,
    'Accept' => 'application/json',
    'Content-Type' => 'application/json'
];
$body = null;
$headers = $signature->generateSignatureHeaders($headers, $endpoint, "GET", $body);
[...]
```

and my example-config.json:

```
{
  "digestAlgorithm": "sha-256",
  "algorithm": "ED25519",
  "privateKey": "./keys/ed25519/privatekey.pem",
  "jwe": "eyJ6aX...",
  "signatureParams": [
    "content-digest",
    "x-ebay-signature-key",
    "@method",
    "@path",
    "@authority"
  ]
}
```

One thing I noticed is that I initially used an access token from a different app of mine that didn't match the JWE. In case you have multiple apps, please make sure to use matching access tokens and JWEs. Can you post the exact response that you receive? And please check if your code and config looks any different from the one I posted here.

**Comment by piniyini** [comment]
Hello @uherberg 

Without `"content-digest"` I get a success response
headers are
`    [Authorization] => Bearer v^1.1#...wAA
    [Accept] => application/json
    [Content-Type] => application/json
    [x-ebay-signature-key] => eyJ...zWA
    [Signature-Input] => sig1=("x-ebay-signature-key" "@method" "@path" "@authority");created=1681394668
    [Signature] => sig1=:UWQk5GFFtlCWOEs68xZty6RvZAXd8O8XeHwN99rcfI0PxIdmzX+P/cABOUFKhzFqNu+OCjKDeKwZit7luQrDAw==:`

And when I include `"content-digest"` in `signatureParams` the response fails, headers are
`    [Authorization] => Bearer v^1.1#...wAA
    [Accept] => application/json
    [Content-Type] => application/json
    [x-ebay-signature-key] => eyJ...zWA
    [Signature-Input] => sig1=("x-ebay-signature-key" "@method" "@path" "@authority");created=1681394765
    [Signature] => sig1=:VJp6xQMoaqymaEozm1CyHLJ2ReNQwQ2e2Ujvoj8UvqTQr9IfrJTOFUISop0IWVfY1KyQzoJzDBzeMgk4gFlXBg==:

response: 
{
  "errors": [
    {
      "errorId": 215122,
      "domain": "ACCESS",
      "category": "REQUEST",
      "message": "Signature validation failed",
      "longMessage": "Signature validation failed to fulfill the request."
    }
  ]`

This is what `config.json` looks like 
`{
  "digestAlgorithm": "sha-256",
  "algorithm": "Ed25519",
  "privateKey": "/var/www/vendor/digital-signature-php-sdk/examples/keys/ed25519/privatekey.pem",
  "jwe": "eyJ...zWA",
  "signatureParams": [
    "x-ebay-signature-key",
    "@method",
    "@path",
    "@authority"
  ]
}`

**Comment by uherberg** [comment]
@piniyini My best guess is that you use a different application for JWE and token. Can you try requesting a new JWE for the app, and make sure to request the user token from the same app? I get the same error when I get a token for a different app than the JWE I got.
I added two separate examples, for GET and POST. I still can't reproduce the error you are seeing

**Comment by uherberg** [comment]
@piniyini I did some more testing myself and found some instabilities in our sandbox environment that could also explain this behavior. Can you try again on your end if this is now resolved on the sandbox environment? Please also test it on production if you can.

**Comment by mianalise** [comment]
Hello @uherberg,
I have installed that repo using 

> composer require ebay/digital-signature-php-sdk

and using this config to do

{
      "digestAlgorithm": "sha-256",
      "algorithm": "Ed25519",
      "privateKey": "MC4CAQAwBQYDK2VwBCIEINPcE5yTMogUV2IXs5QV........",
      "jwe": "eyJ6aXAiOiJERUYiLCJraWQiOiJiNmI4ZWY2MC0zODU4LTRiM.......",
      "signatureParams": [
        "content-digest",
        "x-ebay-signature-key",
        "@method",
        "@path",
        "@authority"
      ]
}


and I am submitting GET Request 
But unfortunately I am getting the same error again and again 

> Signature validation failed to fulfill the request

Can you assist this issue please
Thanks

**Comment by mianalise** [comment]
Hi @uherberg 
I am still waiting for your response
Thanks

**Comment by uherberg** [comment]
@mianalise Apologies for the delayed response. https://github.com/eBay/digital-signature-php-sdk/pull/20 should fix this issue. We will merge it tonight, and it should be available tomorrow as version 1.0.7

**Comment by uherberg** [comment]
@mianalise I merged the PR and released 1.0.7. Please try it with that

**Comment by mianalise** [comment]
@uherberg Now getting the response
Thank you very much

**Comment by uherberg** [comment]
@mianalise Great! I am closing the issue then.
